name: Weatherbot
description: Provides weather updates in Slack
runs:
  using: node16
  main: dist/index.js

inputs:
  Latitude:
    description: The latitude of where you want to return the weather.
    required: true
  Longitude:
    description: The longitude of where you want to return the weather.
    required: true
  DarkSkySecretKey:
    description: Your Dark Sky secrety key. Use a respository secret https://docs.github.com/en/actions/security-guides/encrypted-secrets
    required: true
  SlackChannel:
    description: The Slack channel to post the weather status.
    required: true
  SlackWebHookUrl:
    description: Your Slack webhook URL. Use a respository secret https://docs.github.com/en/actions/security-guides/encrypted-secrets
    required: true
